name: too_good_to_go_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  country_picker: ^2.0.18
  flutter_animate: ^4.5.0
  pinput: ^4.0.0
  persistent_bottom_nav_bar: ^5.0.2
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.0
  easy_localization: ^3.0.5
  get_storage: ^2.1.1
  device_preview: ^1.1.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.8
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  onesignal_flutter: ^5.1.5
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  readmore: ^3.0.0
  flutter_stripe: ^10.1.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  haptic_feedback: ^0.4.2
  share:
  win32: ^5.7.2
  jiffy: ^6.3.1







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

